### ISSUE TITLE
Potential name confusion...

### ISSUE THREAD

**Issue by commadelimited** [sdeering/free-jquery-mobile-icon-pack#1]
Howdy...while I don't have a copyright on the name "jQuery Mobile Icon Pack" it is already in use, and has been for several years now (since 2012). I'd appreciate you changing the name to avoid confusion with my project:

https://github.com/commadelimited/jQuery-Mobile-Icon-Pack

**Comment by commadelimited** [comment]
Following up on this. Please respond.

**Comment by sdeering** [comment]
@commadelimited  Sure mate I don't mind changing it, what would you suggest?
Also, I see there is a 301 redirect which will be created after rename which is cool https://developer.github.com/changes/2015-04-17-preview-repository-redirects/
